src/Entity/Module.php
<?php

namespace App\Entity;

use App\Repository\ModuleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ModuleRepository::class)
 */
class Module
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $autor;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $featured_image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Categorie::class, mappedBy="module")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->autor;
    }

    public function setAutor(string $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(string $featured_image): self
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setModule($this);
        }

        return $this;
    }

    public function removeCategory(Categorie $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getModule() === $this) {
                $category->setModule(null);
            }
        }

        return $this;
    }
}

src/Form/ModuleType.php
<?php

namespace App\Form;

use FOS\CKEditorBundle\Form\Type\CKEditorType;
use App\Entity\Module;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;



class ModuleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',  TextType::class, [
                    'label' => 'Titre du module',
                    'required' => true,
                    'attr' => [
                        'placeholder' => 'Titre'
            ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez renseigner un titre de module'
                    ])
                ]
            ])

            ->add('autor', TextType::class, [
                'label' => 'Auteur du module',
                'required' => true,
                'attr' => [
                    'placeholder' => 'entrez votre Nom'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez renseigner un Nom'
                    ])
                ]
            ])

            ->add('content', CKEditorType::class,[
        'label' => 'contenu du module',
        'required' => true,
        'attr' => [
            'placeholder' => 'entrez votre contenu'
        ],
        'constraints' => [
            new NotBlank([
                'message' => 'Veuillez renseigner un Nom'
            ])
        ]
    ])

            ->add('featured_image', FileType::class, [
                    'label' => 'fichier',
//                    'require'=> 'true',
                    'required' => false])


            ->add('categorie',TextType::class,[
                'label' => 'catégorie',
                'required' => true,
                'attr' => [
                    'placeholder' => 'entrer le catégorie du module'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez renseigner la catégorie'
                    ])
                ]
            ])


//            ->add('categorie',ChoiceType::class,[
//                'label' => 'catégorie',
//                'choices'=>[
//                    'qualité'=>'qualite',
//                    'autre'=>'autre'
//                ],
//                'multiple'=>true,
//                'expanded'=>true,
//                'required' => true,
//            ])
//



            ->add('envoyer', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-dark',
                ]
            ]);

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Module::class,
        ]);
    }
}

src/Controller/ModuleController.php
<?php

namespace App\Controller;

use App\Entity\Module;

use App\Form\ModuleType;
use App\Repository\ModuleRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;




/**
 * @IsGranted("ROLE_ADMIN")
 * @Route("/module")
 */
class ModuleController extends AbstractController
{
    /**
     * @Route("/index", name="module_index", methods={"GET"})
     */
    public function index(ModuleRepository $moduleRepository): Response
    {

        return $this->render('module/index.html.twig', [
            'modules' => $moduleRepository->findAll(),
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/new", name="module_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $module = new Module();

        $form = $this->createForm(ModuleType::class, $module);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $module->setCreatedAt(new\DateTime());
            $module->setUpdatedAt(new \DateTime());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($module);
            $entityManager->flush();

            $this->addFlash(
                'success',
                'Votre module a été publié'
            );


            return $this->redirectToRoute('module_index',['id'=>$module->getId()]);
        }

        return $this->render('module/new.html.twig', [
            'module' => $module,
            'form' => $form->createView(),

        ]);

    }

    /**
     * @IsGranted ("ROLE_USER")
     * @Route("/{id}", name="module_show", methods={"GET"})
     */
    public function show(Module $module): Response
    {
        return $this->render('module/show.html.twig', [
            'module' => $module,
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}/edit", name="module_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Module $module): Response
    {
        $form = $this->createForm(ModuleType::class, $module);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('module_index');
        }

        return $this->render('module/edit.html.twig', [
            'module' => $module,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}", name="module_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Module $module): Response
    {
        if ($this->isCsrfTokenValid('delete'.$module->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($module);
            $entityManager->flush();
        }

        return $this->redirectToRoute('module_index');
    }
}

templates/module/_delete_form.html.twig
<form method="post" action="{{ path('module_delete', {'id': module.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ module.id) }}">
    <button class="btn">Delete</button>
</form>

templates/module/_form.html.twig
{% block body %}

    {{ form_start(form) }}


    {{ form_end(form) }}




    {{ form_start(form) }}


    {{ form_end(form) }}

{% endblock %}

templates/module/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Module{% endblock %}

{% block body %}
    <h1>Edit Module</h1>

{#    {{ include('module/_form.html.twig', {'button_label': 'Update'}) }}#}

{#    <a href="{{ path('module_index') }}">back to list</a>#}

{#    {{ include('module/_delete_form.html.twig') }}#}
{% endblock %}

templates/module/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Module index{% endblock %}

{% block body %}
    <h1 class="row justify-content-center">Page de liste des modules</h1>

    <table class="table">
        <thead>
            <tr>

                <th>Nom</th>
                <th>Auteur</th>
                <th>Contenu</th>
                <th>Document</th>
                <th>Date de publication</th>
                <th>Date de mise à jour</th>
                <th>Categorie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
  <button>      <a href="{{ path('module_new') }}">Créer un nouveau module</a></button>

        {% for module in modules %}
            <tr>

                <td>{{ module.name }}</td>
                <td>{{ module.autor }}</td>
                <td>{{ module.content|raw }}</td>

                <td>{{ module.featuredImage }}</td>
                <td>{{ module.createdAt ? module.createdAt|date('Y-m-d ') : '' }}</td>
                <td>{{ module.updatedAt ? module.updatedAt|date('Y-m-d ') : '' }}</td>
                <td>{{ module.categorie }}</td>
                <td>
                    <a href="{{ path('module_show', {'id': module.id}) }}">Voir</a>
{#                    <a href="{{ path('module_edit', {'id': module.id}) }}">Modifier</a>#}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">pas de module</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/module/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}Création d'un nouveau module{% endblock %}

{% block body %}
    <h1 class="row justify-content-center">Création du module </h1>



    {{ include('module/_form.html.twig') }}

    <div class="row justify-content-center">

 <button>   <a href="{{ path('module_index') }}">Revenir à la liste des modules</a></button>
    </div>
{% endblock %}

templates/module/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Module{% endblock %}

{% block body %}
        <div class="container text-center">
        <h1>Module</h1>

    <div class="card mb-3">
        <h3 class="card-header row justify-content-center ">{{ module.name }}</h3>

        <p class="card-title">{{ module.createdAt ? module.createdAt|date('Y-m-d H') : '' }}</p>
        <p class="card-title"> {{ module.updatedAt ? module.updatedAt|date('Y-m-d H') : '' }}</p>

        <div class="card-body row justify-content-center ">
        <p class="card-text"> {{ module.content|raw }}</p>

    </div>
    <h8 class="card-comment"> {{ module.featuredImage }} Commentaire </h8>




<div class="container text-center">

 <button><a href="{{ path('module_index') }}">Revenir à la liste</a></button>

{#    <button> <a href="{{ path('module_edit', {'id': module.id}) }}">Modifier</a></button>#}
ici delete  en commentaire car ne devrai pas etre visible par user mais uniquement par admin
    {{ include('module/_delete_form.html.twig') }}
</div>
{% endblock %}